kind: List
apiVersion: v1
items:
  # Create custom namespace qualys
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: {{.Values.qualys.namespace}}
  # Service Account
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: qualys-service-account
      namespace: {{.Values.qualys.namespace}}
  # Role for all permission to qualys namespace
  - kind: Role
    apiVersion: {{.Values.qualys.apiVersion}}
    metadata:
      name: qualys-reader-role
      namespace: {{.Values.qualys.namespace}}
    rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["create", "delete", "deletecollection"]
    - apiGroups: ["batch"]
      resources: ["jobs"]
      verbs: ["get","create", "delete", "deletecollection"]
    - apiGroups: [""]
      resources: ["pods/attach"]
      verbs: ["create"]
  # ClusterRole for read permission to whole cluster
  - kind: ClusterRole
    apiVersion: {{.Values.qualys.apiVersion}}
    metadata:
      name: qualys-cluster-reader-role
    rules:
    - apiGroups: [""]
      resources: ["nodes", "pods/status", "replicationcontrollers/status", "nodes/status"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get","list","watch"]
    - apiGroups: [""]
      resources: ["pods/exec"]
      verbs: ["create"]
    - apiGroups: ["apps"]
      resources: ["replicasets/status", "daemonsets/status", "deployments/status", "statefulsets/status"]
      verbs: ["get"]
    - apiGroups: ["batch"]
      resources: ["jobs/status", "cronjobs/status"]
      verbs: ["get"]
  # RoleBinding to assign permissions in qualys-reader-role to qualys-service-account 
  - kind: RoleBinding
    apiVersion: {{.Values.qualys.apiVersion}}
    metadata:
      name: qualys-reader-rb
      namespace: qualys
    subjects:
    - kind: ServiceAccount
      name: qualys-service-account
      namespace: {{.Values.qualys.namespace}}
    roleRef:
      kind: Role
      name: qualys-reader-role
      apiGroup: rbac.authorization.k8s.io
  # ClusterRoleBinding to assign permissions in qualys-cluster-reader-role to qualys-service-account
  - kind: ClusterRoleBinding
    apiVersion: {{.Values.qualys.apiVersion}}
    metadata:
      name: qualys-cluster-reader-rb
    subjects:
    - kind: ServiceAccount
      name: qualys-service-account
      namespace: {{.Values.qualys.namespace}}
    roleRef:
      kind: ClusterRole
      name: qualys-cluster-reader-role
      apiGroup: rbac.authorization.k8s.io
  - kind: SecurityContextConstraints
    apiVersion: security.openshift.io/v1 
    metadata:
      name: scc-qualys-sensor
    allowHostDirVolumePlugin: true
    allowHostNetwork: true
    allowHostIPC: false
    allowHostPID: false
    allowHostPorts: false
    allowPrivilegedContainer: true
    readOnlyRootFilesystem: false
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: RunAsAny
    users:
    - system:serviceaccount:qualys:qualys-service-account      
  # Qualys Container Sensor pod with 
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: qualys-container-sensor
      namespace: {{.Values.qualys.namespace}}
      labels:
        k8s-app: qualys-cs-sensor
    spec:
      selector:
        matchLabels:
          name: qualys-container-sensor
      updateStrategy:
          type: RollingUpdate
      template:
        metadata:
          labels:
            name: qualys-container-sensor
        spec:
{{- if .Values.qualys.toleration }}
          tolerations:
          # this toleration is to have the daemonset runnable on master nodes
          # Uncomment it if want your masters to run sensor pod
          - key: node-role.kubernetes.io/master
            effect: {{.Values.qualys.tolerationeffect}}
{{- end }}
          serviceAccountName: qualys-service-account
          containers:
          - name: qualys-container-sensor
            image: {{.Values.qualys.image}}
            imagePullPolicy: {{.Values.qualys.imagePullPolicy}}
            resources:
              limits:
                cpu: {{.Values.qualys.cpu}} # Default CPU usage limit on each node for sensor.
{{- if .Values.qualys.sensorContLimitMem }}
                memory: "{{.Values.qualys.sensorContLimitMemValue}}"
              requests:
                memory: "{{.Values.qualys.sensorContRequestMemValue}}"
{{- end }}
            args: {{.Values.qualys.args}}
            env:
            - name: CUSTOMERID
              value: {{.Values.qualys.customerID}}
            - name: ACTIVATIONID
              value: {{.Values.qualys.activationID}}
            - name: POD_URL
              value: {{.Values.qualys.pod_url}}
            - name: QUALYS_SCANNING_CONTAINER_LAUNCH_TIMEOUT
              value: "{{.Values.qualys.containerlaunchtimeout}}"
{{- if .Values.qualys.httpsproxy }}
# uncomment(and indent properly) below section if proxy is required to connect Qualys Cloud
            - name: qualys_https_proxy
              value: {{.Values.qualys.httpsproxyvalue}}
{{- end }}
            - name: QUALYS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUALYS_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- if and .Values.qualys.sensorContLimitMem .Values.qualys.scanningContMem }}
            - name: QUALYS_SCANNING_CONTAINER_MEMORYREQUESTMB
              value: "{{.Values.qualys.scanningContReqMemValue}}"
            - name: QUALYS_SCANNING_CONTAINER_MEMORYLIMITMB
              value: "{{.Values.qualys.scanningContLimitMemValue}}"
{{- end }}
            volumeMounts:
            - mountPath: /var/run/crio/crio.sock
              name: socket-volume
              readOnly: true
{{- if .Values.qualys.withpersistentvol }}
            - mountPath: /usr/local/qualys/qpa/data
              name: persistent-volume
{{- end }}
            - mountPath: /usr/local/qualys/qpa/data/conf/agent-data
              name: agent-volume
            - mountPath: /var/lib/containers/storage
              name: container-storage
{{- if .Values.qualys.proxycert }}
# uncomment(and indent properly) below section if proxy(with CA cert) required to connect Qualys Cloud
            - mountPath: /etc/qualys/qpa/cert/custom-ca.crt
              name: proxy-cert-path
{{- end }}
            securityContext:
              privileged: true
          volumes:
            - name: socket-volume
              hostPath:
                path: /var/run/crio/crio.sock
                type: Socket
{{- if .Values.qualys.withpersistentvol }}
            - name: persistent-volume
              hostPath:
                path: {{.Values.qualys.persistentvolhostpath}}
                type: DirectoryOrCreate
{{- end }}
            - name: agent-volume
              hostPath:
                path: /etc/qualys
                type: DirectoryOrCreate
{{- if .Values.qualys.proxycert }}
# uncomment(and indent properly) below section if proxy(with CA cert) required to connect Qualys Cloud
            - name: proxy-cert-path
              hostPath:
                path: {{.Values.qualys.proxycertpath}}
                type: File
{{- end }}
            - name: container-storage
              hostPath:
                path: /var/lib/containers/storage
          hostNetwork: true
